apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak-cleaner.serviceAccountName" . }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "keycloak-cleaner.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if not .Values.serviceAccount.create }}
# NOTE: ServiceAccount creation is disabled.
# Ensure the referenced ServiceAccount exists in the cluster.
{{- end }}
